### ISSUE TITLE
多module之间的资源文件的引用

### ISSUE THREAD

**Issue by marinLiu** [mqzhangw/AndroidComponent#2]
你的Demo代码过少，看不出来什么，我建立一个公共的Module，用来存放公共的Java代码和res资源文件，引用java代码没有问题，但是引用layout文件会找不到，drawable之类的可以找到，但是需要import一个新的R文件，这样在一个Activity里就有2个R文件的引用了。关于这个不知作者有没有什么体会，希望不吝赐教，谢谢

**Comment by mqzhangw** [comment]
你说的问题我觉得都不应该存在，不会只能找到drawable但是找不到layout，并且resource在编译的时候会有merge的过程，使用当前的module的R就可以了。你可以拉一下我新建的dev_res分支，里面app组件的mainactivity使用的就是basicres中的layout文件，没有出现你说的上面两个问题。
