### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by Jusenr** [mqzhangw/AndroidComponent#3]
sharecomponent  -->Activity的资源文件   添加一个Textview属性     

运行 app  的share模块不同步 

运行reader  的share模块同步

运行share  的share模块同步 

app 的share模块是怎摸使其同步资源或者修改呢？

**Comment by mqzhangw** [comment]
不太明白你的意思，可否更详细一下，把代码也最好贴一下

**Comment by Jusenr** [comment]
知道问题出在哪里了。

module或者modulePackage:module，前者直接引用module工程，后者使用componentrelease中已经发布的aar。

**Comment by Jusenr** [comment]
module或者modulePackage:module，前者直接引用module工程，后者使用componentrelease中已经发布的aar。
