### ISSUE TITLE
关于ui的耦合问题

### ISSUE THREAD

**Issue by imyyg2008** [mqzhangw/AndroidComponent#5]
有这样的场景，使用了一个开源库里的view，把这个库单独作为一个module，现在在主module里怎么使用这个view，如果直接在布局文件里使用的话就会造成主module与开源库的module代码耦合，当然根据你的demo可以在service里通过提供类似getXxxView方法，主module可以获得到此View，但是这样做的缺点是1.只能通过代码动态添加view，不能写布局文件。如果现有项目里已经使用了布局文件方式，然后全部改成使用代码方式也比较麻烦。2.无法使用此view里的方法。请问一下，有没有比较好的方法来解决类似ui代码的耦合问题。谢谢

**Comment by mqzhangw** [comment]
对于开源库，不应该当做一个组件component来处理，应该是一个依赖库library。component是抽离的业务模块，它的层级是在library之上的。我的建议是要么把这个开源库直接在某个组件中直接引用，要么交给basicres来引入，后者就可以让所有的组件直接使用了。
但是也的确存在一个组件提供view给其他组件使用的情况，只能动态添加的问题可能暂时没有解决办法，不过从理论上来讲，也不应该在xml中直接使用，这样造成的耦合就太严重了，后面改一下view名字就直接崩溃了。而调用其方法比较简单，只需要把view对外暴露的接口定义在这个组件提供的服务中，这样其他组件就可以根据接口来编程了。

**Comment by mqzhangw** [comment]
如果不想大规模的改动xml，其实可以使用装饰器的模式，新建一个view，里面调用组件化提供的view方法。这样也可以做到解耦

**Comment by imyyg2008** [comment]
了解，谢谢提供思路，我在试试
