### ISSUE TITLE
一个完整的功能模块是如何编译为*.aar添加到componentrelease文件夹下的？

### ISSUE THREAD

**Issue by Jusenr** [mqzhangw/AndroidComponent#6]
一个完整的功能模块（如sharecomponent），是如何编译为*.aar添加到componentrelease文件夹下的，提供给app依赖的呢？

当然，可以编译该模块，然后复制其build/outputs/aar/*.aar文件到componentrelease文件夹下。

其他的方法呢？

**Comment by mqzhangw** [comment]
你如果使用了源码中的com.dd. comgradle这个插件，只要手动把inRunAlone改为false，运行mudule:assembleRelease就会自动将生成的aar拷贝到componentrelease文件夹下面。注意此处是唯一需要修改inRunAlone的情况，如果想单独运行，请将inRunAlone修改会true。（修改inRunAlone之后需要sync才会生效）
