### ISSUE TITLE
两个模块跳转不通，我不知道怎磨回事？

### ISSUE THREAD

**Issue by Jusenr** [mqzhangw/AndroidComponent#7]
app

    UIRouter.getInstance().openUri(getApplicationContext(), "putao://login", bundle);

moduel 1

private static final String SCHME = "putao";

    private static final String SHAREHOST = "login";

就是无法跳转。。。https://github.com/Jusenr/android_paiband

**Comment by mqzhangw** [comment]
原因可能是你的LoginApplike没有注册，如果你使用的是字节码注入的方式注册，你可以看一下打印的日志，看看是否打印出applicationlike is XXX 的日志，如果没有估计是插入不成功。有时候instant run开启会不成功，也有可能是你改了包名但是在ComCodeTransform类里面还是用的我写死的demo的包名com.mrzhang.component.componentlib.applicationlike.IApplicationLike，这里需要你自己修改。

**Comment by mqzhangw** [comment]
此外，库已经转移到https://github.com/luojilab/DDComponentForAndroid，欢迎到新库提交issue

**Comment by Jusenr** [comment]
那就是包名的问题了  谢谢
